---
title: "CyberBullying_Analysis"
author: "Ojoniko Nathan Abah"
date: "March 6, 2019"
output: html_document
---


```{r xml}
install.packages("XML")
```
```{r load}
library(XML)
url <- "file:///C:/Users/Ojoniko%20Nathan%20Abah/Desktop/cyberbullying_dataset/DataReleaseDec2011/XMLMergedFile.xml"
xmldoc <- xmlParse(url)
rootNode <- xmlRoot(xmldoc)
rootNode[1]
data <- xmlSApply(rootNode, function(x) xmlSApply(x, xmlValue))
cd.catalog <- data.frame(t(data), row.names = NULL)
cd.catalog[1:2,]
```

```{r}
library(XML)
url <- "file:///C:/Users/Ojoniko%20Nathan%20Abah/Desktop/cyberbullying_dataset/DataReleaseDec2011/XMLMergedFile.xml"
xmlfile <- xmlTreeParse(url)
class(xmlfile)
topxml <- xmlRoot(xmlfile)
topxml <- xmlSApply(topxml, function(x) xmlSApply(x, xmlValue))
xml_df <- data.frame(t(topxml), row.names = NULL)
```
```{r}
require(xml2)
URL <- "file:///C:/Users/Ojoniko%20Nathan%20Abah/Desktop/cyberbullying_dataset/DataReleaseDec2011/XMLMergedFile.xml"
XML_data <- read_xml(URL)
```

```{r}

## Reading Excel files

  ### Save the csv file above into your working directory as an Excel sheet first
  
  mywd <- "C:/Users/Ojoniko Nathan Abah/Desktop/"
  setwd(mywd)
  
```

